cmake_minimum_required(VERSION 3.18 FATAL_ERROR)

set(SPOOKYHASH_VERSION "1.0")
set(SPOOKYHASH_LANGUAGES )
set(SPOOKYHASH_CODESIGNING )
set(SW_VERS "")
set(UNAME_M "")

if (APPLE)
    list(APPEND SPOOKYHASH_LANGUAGES "C")
    list(APPEND SPOOKYHASH_LANGUAGES "CXX")
    list(APPEND SPOOKYHASH_LANGUAGES "OBJC")
    list(APPEND SPOOKYHASH_LANGUAGES "OBJCXX")
    execute_process(COMMAND sw_vers -productVersion OUTPUT_VARIABLE SW_VERS ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)
    if ("${CMAKE_GENERATOR}" MATCHES "Xcode")
        execute_process(COMMAND uname -m OUTPUT_VARIABLE UNAME_M ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)
        if (NOT "$ENV{SYSROOT}" STREQUAL "")
            set(SYSROOT "$ENV{SYSROOT}")
        else()
            execute_process(COMMAND xcodebuild -version -sdk macosx Path OUTPUT_VARIABLE SYSROOT ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)
        endif()
        if (NOT EXISTS "${SYSROOT}")
            message(FATAL_ERROR "SYSROOT does not exist!")
        endif()
        set(CMAKE_OSX_SYSROOT "${SYSROOT}" CACHE STRING "CMAKE_OSX_SYSROOT" FORCE)
        if ("${CMAKE_OSX_ARCHITECTURES}" STREQUAL "")
            if ("${UNAME_M}" MATCHES "arm")
                set(CMAKE_OSX_ARCHITECTURES "arm64" CACHE STRING "CMAKE_OSX_ARCHITECTURES" FORCE)
            else()
                set(CMAKE_OSX_ARCHITECTURES "$(ARCHS_STANDARD)" CACHE STRING "CMAKE_OSX_ARCHITECTURES" FORCE)
            endif()
        endif()
    endif()
    execute_process(COMMAND security find-identity -v -p codesigning OUTPUT_VARIABLE SECURITY_FOUND_IDENTITY ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)
    set(PATTERN " ")
    foreach(IDX RANGE 1 40 1)
        string(APPEND PATTERN "[a-fA-F0-9]")
    endforeach()
    string(APPEND PATTERN " ")
    string(REGEX MATCH "${PATTERN}" IDENTITY "${SECURITY_FOUND_IDENTITY}")
    if (NOT "${IDENTITY}" STREQUAL "")
        string(STRIP "${IDENTITY}" SPOOKYHASH_CODESIGNING)
    endif()
else()
    list(APPEND SPOOKYHASH_LANGUAGES "C")
    list(APPEND SPOOKYHASH_LANGUAGES "CXX")
    if (MINGW)
        list(APPEND SPOOKYHASH_LANGUAGES "RC")
    endif()
endif()

macro(set_option var default type docstring)
	  if (("${type}" STREQUAL "STRING" AND "${var}" STREQUAL "") OR NOT DEFINED ${var})
		    set(${var} ${default})
	  endif()
	  set(${var} ${${var}} CACHE ${type} ${docstring} FORCE)
endmacro()

if ("${CMAKE_GENERATOR}" MATCHES "Xcode" AND NOT "${SW_VERS}" STREQUAL "")
    string(REPLACE "." ";" SW_VERS_MAJOR "${SW_VERS}")
    list(POP_FRONT SW_VERS_MAJOR SW_VERS_HEAD)
    set(SW_VERS "${SW_VERS_HEAD}")
    set_option(CMAKE_OSX_DEPLOYMENT_TARGET "${SW_VERS}" STRING "Choose the minimum MacOS deployment version")
endif()
set_option(CMAKE_BUILD_TYPE "Debug" STRING "Choose the type of build config variant (\"Debug\" or \"Release\")")
set_option(SPOOKYHASH_LINKAGE "STATIC" STRING "Choose the type of library linkage for the libspookyhash target (\"STATIC\" or \"SHARED\")")
set_option(SPOOKYHASH_BINARY "ON" STRING "Whether or not to build the spookyhash executable target (\"ON\" or \"OFF\")")
set_option(SPOOKYHASH_TESTING "OFF" STRING "Whether or not to run unit tests (\"ON\" or \"OFF\")")

project(spookyhashproject VERSION ${SPOOKYHASH_VERSION} LANGUAGES ${SPOOKYHASH_LANGUAGES})

list(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_SOURCE_DIR}/cmake)

set(CMAKE_SHARED_LIBRARY_PREFIX "")
set(CMAKE_STATIC_LIBRARY_PREFIX "")
if (NOT "${CMAKE_BUILD_TYPE}" STREQUAL "Release")
    set(CMAKE_DEBUG_POSTFIX "${CMAKE_BUILD_TYPE}")
endif()

set(SPOOKYHASH_DEF )
#list(APPEND SPOOKYHASH_DEF "SPOOKYHASH_VERSION=${SPOOKYHASH_VERSION}")
if ("${SPOOKYHASH_LINKAGE}" STREQUAL "SHARED")
    list(APPEND SPOOKYHASH_DEF SPOOKYHASH_LIBRARY_TYPE_SHARED)
    set(BUILD_SHARED_LIBS ON)
else()
    list(APPEND SPOOKYHASH_DEF SPOOKYHASH_LIBRARY_TYPE_STATIC)
endif()
if ("${CMAKE_BUILD_TYPE}" STREQUAL "Debug")
    list(APPEND SPOOKYHASH_DEF SPOOKYHASH_DEBUG)
endif()
if ("${CMAKE_CXX_COMPILER_ID}" MATCHES "Clang")
    list(APPEND SPOOKYHASH_DEF SPOOKYHASH_CLANG)
endif()
if (APPLE)
    list(APPEND SPOOKYHASH_DEF SPOOKYHASH_OS_APPLE)
elseif (ANDROID)
    list(APPEND SPOOKYHASH_DEF SPOOKYHASH_OS_ANDROID)
elseif (MINGW OR MSVC)
    list(APPEND SPOOKYHASH_DEF SPOOKYHASH_OS_WINDOWS)
    if (MINGW)
        list(APPEND SPOOKYHASH_DEF SPOOKYHASH_MINGW)
    endif()
else()
    list(APPEND SPOOKYHASH_DEF SPOOKYHASH_OS_LINUX)
endif()
if ("${CMAKE_SIZEOF_VOID_P}" STREQUAL "4")
    list(APPEND SPOOKYHASH_DEF SPOOKYHASH_BITNESS_32)
else ()
    list(APPEND SPOOKYHASH_DEF SPOOKYHASH_BITNESS_64)
endif ()
include(TestBigEndian)
TEST_BIG_ENDIAN(IS_BIG_ENDIAN)
if(IS_BIG_ENDIAN)
    list(APPEND SPOOKYHASH_DEF SPOOKYHASH_ENDIANNESS_BIG)
else()
    list(APPEND SPOOKYHASH_DEF SPOOKYHASH_ENDIANNESS_LITTLE)
endif()

include_directories(${CMAKE_CURRENT_LIST_DIR})

set(SPOOKYHASH_LIB_DEF )
foreach(DEF IN LISTS SPOOKYHASH_DEF)
    list(APPEND SPOOKYHASH_LIB_DEF ${DEF})
endforeach()
list(APPEND SPOOKYHASH_LIB_DEF SPOOKYHASH_TARGET_TYPE_LIBRARY)

set(SPOOKYHASH_LIB_SRC )
set(SPOOKYHASH_LIB_INC )

list(APPEND SPOOKYHASH_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/SpookyV2.cpp)
list(APPEND SPOOKYHASH_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/SpookyV2.h)

list(APPEND SPOOKYHASH_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/SpookyV2.h)

add_library(libspookyhash ${SPOOKYHASH_LINKAGE} ${SPOOKYHASH_LIB_SRC})
if ("${SPOOKYHASH_LINKAGE}" STREQUAL "SHARED" AND (APPLE OR WINDOWS))
    install(TARGETS libspookyhash RUNTIME DESTINATION ${CMAKE_INSTALL_PREFIX}/bin ARCHIVE DESTINATION ${CMAKE_INSTALL_PREFIX}/bin LIBRARY DESTINATION ${CMAKE_INSTALL_PREFIX}/bin FRAMEWORK DESTINATION ${CMAKE_INSTALL_PREFIX}/bin)
else()
    install(TARGETS libspookyhash)
endif()
target_compile_features(libspookyhash PRIVATE cxx_std_17)
set_target_properties(libspookyhash PROPERTIES LINKER_LANGUAGE CXX)
target_compile_definitions(libspookyhash PRIVATE ${SPOOKYHASH_LIB_DEF})
#set_target_properties(libspookyhash PROPERTIES PUBLIC_HEADER "${SPOOKYHASH_LIB_INC}")
install(FILES ${SPOOKYHASH_LIB_INC} DESTINATION ${CMAKE_INSTALL_PREFIX}/include/libspookyhash)

set(SPOOKYHASH_BIN_DEF )
foreach(DEF IN LISTS SPOOKYHASH_DEF)
    list(APPEND SPOOKYHASH_BIN_DEF ${DEF})
endforeach()
list(APPEND SPOOKYHASH_BIN_DEF SPOOKYHASH_TARGET_TYPE_EXECUTABLE)

set(SPOOKYHASH_BIN_SRC )
list(APPEND SPOOKYHASH_BIN_SRC ${CMAKE_CURRENT_LIST_DIR}/TestSpookyV2.cpp)

if ("${SPOOKYHASH_BINARY}" STREQUAL "ON")
    add_executable(spookyhash ${SPOOKYHASH_BIN_SRC})
    add_dependencies(spookyhash libspookyhash)
    install(TARGETS spookyhash RUNTIME DESTINATION ${CMAKE_INSTALL_PREFIX}/bin BUNDLE DESTINATION ${CMAKE_INSTALL_PREFIX}/bin)
    target_compile_features(spookyhash PRIVATE cxx_std_17)
    set_target_properties(spookyhash PROPERTIES LINKER_LANGUAGE CXX)
    if ("${SPOOKYHASH_LINKAGE}" STREQUAL "SHARED")
        target_link_libraries(spookyhash PRIVATE libspookyhash)
    else()
        target_link_libraries(spookyhash PRIVATE libspookyhash)
    endif()
    target_compile_definitions(spookyhash PRIVATE ${SPOOKYHASH_BIN_DEF})
    if (APPLE)
        add_custom_command(TARGET spookyhash POST_BUILD COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_INSTALL_PREFIX}/bin COMMENT "Make binary installation" WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR})
        add_custom_command(TARGET spookyhash POST_BUILD COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_INSTALL_PREFIX}/lib COMMENT "Make library installation" WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR})
        add_custom_command(TARGET spookyhash POST_BUILD COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_INSTALL_PREFIX}/include COMMENT "Make header installation" WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR})
        if ("${CMAKE_GENERATOR}" MATCHES "Xcode" AND "${CMAKE_BUILD_TYPE}" STREQUAL "Debug" AND NOT "${SW_VERS}" STREQUAL "")
            #set_target_properties(spookyhash PROPERTIES XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY "Apple Development")
            #set_target_properties(spookyhash PROPERTIES XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY "-")
        endif()
        add_custom_command(TARGET spookyhash POST_BUILD COMMAND ${CMAKE_INSTALL_NAME_TOOL} -add_rpath "@executable_path/" $<TARGET_FILE:spookyhash> || :)
        string(LENGTH "${SPOOKYHASH_CODESIGNING}" LEN)
        if ("${LEN}" STREQUAL "40" AND "${CMAKE_BUILD_TYPE}" STREQUAL "Release" AND NOT "${SW_VERS}" STREQUAL "")
            add_custom_command(TARGET spookyhash POST_BUILD COMMAND codesign --sign "${SPOOKYHASH_CODESIGNING}" --force --verbose --timestamp --deep $<TARGET_FILE:spookyhash> || :)
            if ("${SPOOKYHASH_LINKAGE}" STREQUAL "SHARED")
                add_custom_command(TARGET spookyhash POST_BUILD COMMAND codesign --sign "${SPOOKYHASH_CODESIGNING}" --force --verbose --timestamp --deep $<TARGET_FILE:libspookyhash> || :)
            endif()
        endif()
    endif()
endif()

